### PR TITLE
add CI for haskell through build_hs.sh

### LINKED ISSUE #1: Run slides/build_hs.sh in CI
The script [slides/build_hs.sh](https://github.com/smelc/tn-fp-haskell-course/blob/308757c8332dc510445c6b80a151871e4494fa7b/slides/build_hs.sh) checks that Haskell snippets from the slides (i.e. from the `slides/course*.md` files) are valid, using my [exdown fork](https://github.com/smelc/exdown) and then compiling with cabal.

This issue keeps track of doing this check in the CI. So far I have been using this script only locally.

The new CI check should use GHC 8.10.4, because this is the version I use in [travaux pratiques](https://github.com/smelc/tn-fp-haskell-course/blob/308757c8332dc510445c6b80a151871e4494fa7b/tps/README.md).

### PR DESCRIPTION
**Pull request by tbagrel1**

### CODE REVIEW

**Comment by tbagrel1** [comment]
Closes #1

**Comment by tbagrel1** [comment]
I used GHC 8.10.7 because 8.10.4 doesn't seem to be available any longer in nixpkgs.
We should also try to see if the CI effectively fails when some invalid haskell code is written in a markdown file.

**Comment by tbagrel1** [comment]
It indeed fails on invalid haskell code, see https://github.com/smelc/tn-fp-haskell-course/runs/7633678566

**Comment by smelc** [comment]
LGTM :champagne:

Just one remark. This looks clunky:

image

Could you easily fix it? If not, let's not bother.

**Comment by tbagrel1** [comment]
> LGTM champagne
> 
> Just one remark. This looks clunky:
> 
> image
> 
> Could you easily fix it? If not, let's not bother.

I think that I solved the issue with my latest commit, but the build takes a little bit longer (I suppose that it might need to redownload the nixpkgs thing several times?). We should ask the help of a nix guru to see if what I did makes sense.

**Comment by smelc** [comment]
> but the build takes a little bit longer

@tbagrel1> It takes less than 3 minutes, we're good, hence merging :slightly_smiling_face:

Thanks for your help, very much appreciated! :100:

**Pull request merged**
